version: '3'
services:
  web:
    restart: always
    build: .
    ports:
      - '5000:5000'
    links:
      - mysql
    command: pipenv run flask run
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    links:
      - web
  mysql:
    restart: always
    image: mysql:5.7
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
