version: '3'
services:
  flask:
    restart: always
    build: .
    ports:
      - '5000:5000'
    links:
      - mysql
    command: pipenv run gunicorn -w4 -b 0.0.0.0:5000 wsgi:app
  front:
    build: ./rest
    restart: always
    ports:
      - "80:80"
    links:
      - flask
  mysql:
    restart: always
    image: mysql:5.7
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
