"""empty message

Revision ID: 92cbd176de53
Revises: 31bc9783910f
Create Date: 2018-05-11 15:54:00.711655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92cbd176de53'
down_revision = '31bc9783910f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('post_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tag',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name='post_tag_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='post_tag_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('article_tag')
    # ### end Alembic commands ###
