"""empty message

Revision ID: cccf91862965
Revises: 53c84b665e1c
Create Date: 2018-05-13 22:14:26.149424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccf91862965'
down_revision = '53c84b665e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('slug', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'article', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='unique')
    op.drop_column('article', 'slug')
    # ### end Alembic commands ###
